version: '2'

services:
  redis:
    image: "redis:alpine"
    container_name: "q4_hotmilhas_redis"
    expose:
      - 6379
  mongodb:
    image: mongo:latest
    container_name: "q4_hotmilhas_mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.docker/data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --port 27017 --smallfiles --logpath=/dev/null
  web:
    build: .
    container_name: "q4_hotmilhas_web"
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    links:
      - redis
      - mongodb
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=production
      - PORT=3000
    command:
      sh -c 'npm i && node src/index.js'

