version: '2'

services:
  redis:
    image: "redis:alpine"
    container_name: "q4_hotmilhas_redis_test"
    expose:
      - 6379
  mongodb:
    image: mongo:latest
    container_name: "q4_hotmilhas_mongodb_test"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.docker/data/db:/data/db
    ports:
        - 27050:27050
    command: mongod --port 27050 --smallfiles --logpath=/dev/null
  web:
    build: .
    container_name: "q4_hotmilhas_web_test"
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
    links:
      - redis
      - mongodb
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=test
      - PORT=3002
    command:
      sh -c 'npm i && node_modules/.bin/jest'

