version: '2'

services:
  redis:
    image: "redis:alpine"
    container_name: "q4_hotmilhas_redis_development"
    expose:
      - 6379
  mongodb:
    image: mongo:latest
    container_name: "q4_hotmilhas_mongodb_development"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.docker/data/db:/data/db
    ports:
        - 27050:27050
    command: mongod --port 27050 --smallfiles --logpath=/dev/null
  mongogui:
    container_name: "q4_hotmilhas_mongogui_development"
    image: mongo-express:0.44
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_PORT=27050
    ports:
      - "8081:8081"
    links:
      - web
      - mongodb
    depends_on:
      - web
      - mongodb
  redisgui:
    container_name: "q4_hotmilhas_redisgui_development"
    image: marian/rebrow
    ports:
      - "8082:5001"
    links:
      - redis
    depends_on:
      - redis
  web:
    build: .
    container_name: "q4_hotmilhas_web_development"
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    links:
      - redis
      - mongodb
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3001
    command:
      sh -c 'npm i && node_modules/.bin/nodemon src/index.js'

